# Generated by Django 5.1.4 on 2025-01-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_moviedata_typ"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviedata",
            name="typ",
            field=models.CharField(default="action", max_length=200),
        ),
    ]
