# Generated by Django 5.1.4 on 2025-01-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_moviedata_typ"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="image",
            field=models.ImageField(
                default="images/None/Noimg.jpg", upload_to="images/"
            ),
        ),
    ]
