# Generated by Django 5.1.6 on 2025-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_orderdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderdetail",
            name="stripe_payment_intent",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
