# Generated by Django 5.1.4 on 2025-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
